version: "3.8"
services:
  mongo-primary:
    image: mongo
    container_name: mongo-primary
    command: ["--replSet", "rs0"]
    ports: 
      - "27017:27017"
    volumes:
      - mongo-primary-data:/data/db
    networks: 
      - mongo-cluster

  mongo-secondary:
    image: mongo
    container_name: mongo-secondary
    command: ["--replSet", "rs0"]
    ports:
      - "27018:27017"
    volumes:
      - mongo-secondary-data:/data/db
    networks:
      - mongo-cluster

  mongo-arbiter:
    image: mongo
    container_name: mongo-arbiter
    command: ["--replSet", "rs0"]
    ports:
      - "27019:27017"
    volumes:
      - mongo-arbiter-data:/data/db
    networks:
      - mongo-cluster

volumes:
  mongo-primary-data:
  mongo-secondary-data:
  mongo-arbiter-data:

networks:
  mongo-cluster:
    driver: bridge