version: "3.8"
services:
  mongo-primary:
    build: .
    container_name: mongo-primary
    command: ["--replSet", "rs0", "--auth", "--keyFile", "/etc/mongo-keyfile"]
    ports: 
      - "27017:27017"
    volumes:
      # - ./mongo-keyfile:/etc/mongo-keyfile:ro
      - mongo-primary-data:/data/db
    networks: 
      - mongo-cluster

  mongo-secondary:
    build: .
    container_name: mongo-secondary
    command: ["--replSet", "rs0", "--auth", "--keyFile", "/etc/mongo-keyfile"]
    ports:
      - "27018:27017"
    volumes:
      # - ./mongo-keyfile:/etc/mongo-keyfile:ro
      - mongo-secondary-data:/data/db
    networks:
      - mongo-cluster

  mongo-arbiter:
    build: .
    container_name: mongo-arbiter
    command: ["--replSet", "rs0", "--auth", "--keyFile", "/etc/mongo-keyfile"]
    ports:
      - "27019:27017"
    volumes:
      # - ./mongo-keyfile:/etc/mongo-keyfile:ro
      - mongo-arbiter-data:/data/db
    networks:
      - mongo-cluster

volumes:
  mongo-primary-data:
  mongo-secondary-data:
  mongo-arbiter-data:

networks:
  mongo-cluster:
    driver: bridge